### ISSUE TITLE
Question about the self-hosting software

### ISSUE THREAD

**Issue by Joker666** [keyvank/30cc#67]
You wrote -
- Imagine `30cc` gets strong enough to be able to compile itself.
- I will first compile `30cc` with `gcc` to get the `30cc` compiler's binary.
- I will then use the `gcc`-generated `30cc` binary file to compile the `30cc` again.
- I now have a `30cc`-compiled version of `30cc`, which I can use for further developing the compiler!
- I can forget about `gcc`, as if it never existed! Beautiful hah? `30cc` is now all alive by itself!

What if you want to add a new syntax not recognized by the previous version of the 30cc compiler? I know most compilers are doing what you are doing now, like the Golang compiler. However, I always wondered about this process.

**Comment by keyvank** [comment]
You'll use the previous version of the compiler to build the updated source-code, then you'll have the new version of the compiler which supports the new language construct. Now you can use the new language construct in the source-code of the compiler itself.
